spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lvshop?serverTimezone=Asia/Shanghai&amp&useSSL=true&amp&useUnicode=true&amp&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j
  #spring: mvc: pathmatch: matching-strategy: ANT_PATH_MATCHER
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#    static-path-pattern: /**
mybatis:
  type-aliases-package: com.lvshopadmin.pojo
  mapper-locations: classpath:mapper/*.xml
